name: Split notebooks by language
on:
  push:
    paths:
      - 'notebooks'
                
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - run: |
            date > generated.txt
            # Note: the following account information will not work on GHES
            git config user.name "github-actions[bot]"
            git config user.email "3206671+rokgomiscek@users.noreply.github.com"
            git add .
            git commit -m "generated"
            git push
