name: Split notebooks by language
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
            date > generated.txt
            # Note: the following account information will not work on GHES
            git config user.name "rokgomiscek"
            git config user.email "3206671+rokgomiscek@users.noreply.github.com"
            git add .
            git commit -m "generated"
            git push
