name: Split notebooks by language
on: 
    pull_request_target:
        paths:
        - 'notebooks/src/**.ipynb'
        types:
        - closed
jobs:
    convert_and_commit:
        if: github.event.pull_request.merged == true
        permissions:
            contents: write
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./scripts
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name : Remove old files
          run: |
            git rm -r ../notebooks/en
            git rm -r ../notebooks/sl
        - name: Install jupyter and run nbconvert
          run: |
            python -m pip install jupyter
            bash convert.sh
        - name: Commit
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A ../notebooks/en
            git add -A ../notebooks/sl
            git commit -m "Split by language"
            git push
